name: Enable Alias in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test-alias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup alias and enable expansion
        run: |
          alias ll='ls -lah'
          ll  # 直接定义并使用别名
        shell: bash
